name: Build, Test, and Deploy MyWorkout

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-csharp-unit:
    name: Run C# Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web

      - name: Build
        run: dotnet build --configuration Release --no-restore ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web

      - name: Run .NET Tests
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true --configuration Release --collect:"XPlat Code Coverage" --logger trx --results-directory coveragereport-unit --settings ${{github.workspace}}/.runsettings ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web

  validate-csharp:
    name: Validate C# Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web

      - name: Ensure Coalesce has run
        working-directory: ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web
        run: |
            echo 'Running Coalesce'
            dotnet coalesce
            if [ $? -ne 0 ]; then
            echo "`dotnet coalesce` exited with code $?"
            exit 1
            fi
            echo 'Adding Changed Files'
            git add .
            echo 'Checking Diff'
            git diff HEAD --cached --exit-code

      - name: Run dotnet format checks
        run: dotnet format --verify-no-changes --verbosity diagnostic ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web

  validate-and-test-typescript:
    name: Validate and Test TypeScript Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        working-directory: ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web
        run: npm install

      - name: Ensure linter has run
        working-directory: ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web
        run: npm run lint

      - name: Run TS Vite Tests
        working-directory: ColeStewart.MyWorkout/ColeStewart.MyWorkout.Web
        run: npm run test
